### ISSUE TITLE
add support for VS Code

### ISSUE THREAD

**Issue by aguilera51284** [phalcon/volt-sublime-textmate#3]
That is all :)

**Comment by sergii-okhotnyi** [comment]
Done: https://marketplace.visualstudio.com/items?itemName=hunter-dev.volt

**Comment by leocaseiro** [comment]
Hi @sergii-okhotnyi, where's the repo of the vscode? Is the same as this one?

I'd like to implement Auto Format, similar what is happening with the [new Twig Extension](https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2). Thanks

**Comment by sergeyklay** [comment]
@leocaseiro There is

* official repo https://github.com/zephir-lang/zephir-vscode 
* plugin https://marketplace.visualstudio.com/items?itemName=zephir-lang.zephir

**Comment by leocaseiro** [comment]
Thanks @sergii-okhotnyi for the links, but unfortunately, they don't have an auto format on vscode either.

**Comment by sergeyklay** [comment]
@leocaseiro Pull request are always welcome :)
